### ISSUE TITLE
logback-amqpappender的配置问题

### ISSUE THREAD

**Issue by BruceMaa** [knightliao/spring-amqp-logback#1]
你好，我按照你的配置，启动项目后还是不能把日志发送到rabbitMQ中，我的配置文件如下：

<?xml version="1.0" encoding="UTF-8"?>
<configuration>  
	
	<appender name="STDOUT-APPENDER" class="ch.qos.logback.core.ConsoleAppender">    
		<encoder charset="UTF-8">      
			<pattern>%property{HOSTNAME} %d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{15} - %msg%n</pattern>    
		</encoder>  
		<target>System.out</target>  
	</appender>  
	<appender name="STDERR-APPENDER" class="ch.qos.logback.core.ConsoleAppender">    
		<encoder charset="UTF-8">      
			<pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{15} - %msg%n</pattern>    
		</encoder>  
		<target>System.err</target>  
	</appender>
	
	<property resource="rabbitMQ.properties"/>
	
	<appender name="AMQP" class="org.springframework.amqp.rabbit.logback.AmqpAppender">
		<layout>
	        <pattern>%X{sessionId} %date [%thread] %-5level %logger{80} - %msg%n</pattern>
	    </layout>
		<host>${hostname}</host>
		<port>${port}</port>
		<username>${username}</username>
		<password>${password}</password>
		<routingKeyPattern>${routingKeyPattern}</routingKeyPattern>
		<exchangeName>${exchangeName}</exchangeName>
		
		<declareExchange>true</declareExchange>
	    <generateId>true</generateId>
	    <charset>UTF-8</charset>
	    <durable>true</durable>
	    <deliveryMode>PERSISTENT</deliveryMode>
	</appender>
	
	<root level="INFO">    
		<appender-ref ref="AMQP" />  
	</root>
	
</configuration>

可能由于此web项目引用了一个framework项目，在framework项目中也在配置文件中连接了一个消息队列

<rabbit:connection-factory id="connectionFactory" host="" username="" password="" port="" />

项目启动后，有如下红色日志输出：
SLF4J: The following loggers will not work because they were created

SLF4J: during the default configuration phase of the underlying logging system.

SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger

SLF4J: org.springframework.amqp.rabbit.connection.CachingConnectionFactory

SLF4J: org.springframework.amqp.rabbit.core.RabbitAdmin

SLF4J: org.springframework.amqp.rabbit.core.RabbitTemplate

SLF4J: org.springframework.transaction.support.TransactionSynchronizationManager

SLF4J: org.springframework.transaction.support.TransactionSynchronizationUtils

SLF4J: org.springframework.amqp.rabbit.connection.RabbitResourceHolder

SLF4J: org.springframework.amqp.rabbit.connection.ConsumerChannelRegistry

SLF4J: org.springframework.amqp.rabbit.connection.RabbitUtils

不知道你有没有遇到过这类问题，可不可以帮我解惑一下，谢谢了。

**Comment by knightliao** [comment]
看下日志 并没有什么错误啊

**Comment by BruceMaa** [comment]
我改用了继承AppenderBase方法来实现了，这个配置文件的方法最后还是没有成功

**Comment by knightliao** [comment]
那你跑我的程序 你能跑成功吗

**Comment by BruceMaa** [comment]
就是因为没有成功，才转用继承AppenderBase来实现的，好像没有发送到RabbitMQ中，但是也没有报错日志。
应该是我对RabbitMQ和logback还不够熟悉，所以没检查出来是什么问题。

**Comment by knightliao** [comment]
我这边
